In [239]:
import numpy as np

In [240]:
mat0 = np.zeros((6, 3))
for i in range(mat0.shape[0]):
    for j in range(mat0.shape[1]):
        # mat0[i, j] = str(f"{i+1}{j+1}")
        mat0[i, j] = 0
print("nb de lignes pour la propriété d'adjacence", 4*4 + 4*2 + (8+2)*3)
mat0

nb de lignes pour la propriété d'adjacence 54


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [241]:
mat1 = np.zeros((8, 4))
for i in range(mat1.shape[0]):
    for j in range(mat1.shape[1]):
        # mat1[i, j] = str(f"{i+1}{j+1}")
        mat1[i, j] = 0
print("nb de lignes pour la propriété d'adjacence", 12*4 + (12 + 4)*3 + 4*2)
mat1

nb de lignes pour la propriété d'adjacence 104


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [242]:
mat2 = np.zeros((15, 4))
for i in range(mat2.shape[0]):
    for j in range(mat2.shape[1]):
        # mat2[i, j] = str(f"{i+1}{j+1}")
        mat2[i, j] = 0
print("nb de lignes pour la propriété d'adjacence", 13*2*4 + (13*2 + 4)*3 + 4*2)
mat2

nb de lignes pour la propriété d'adjacence 202


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [243]:
def adjacence_properties(mat):
    """ Copier coller pour ajouter propriétés d'adjacence de mat """
    # Coin en haut à gauche
    i, j = 1, 1
    print(f"(adjacent pos{i}{j} pos{i+1}{j})")
    print(f"(adjacent pos{i}{j} pos{i}{j+1})")

    # Première ligne sauf coins
    for j in range(1, mat.shape[1]-1):
        j += 1
        print(f"(adjacent pos{i}{j} pos{i}{j-1})")
        print(f"(adjacent pos{i}{j} pos{i+1}{j})")
        print(f"(adjacent pos{i}{j} pos{i}{j+1})")

    # Coin en haut à droite
    j = mat.shape[1]
    print(f"(adjacent pos{i}{j} pos{i+1}{j})")
    print(f"(adjacent pos{i}{j} pos{i}{j-1})")


    for i in range(1, mat.shape[0]-1):
        # Coté gauche sauf première et dernière ligne
        j = 1
        print(f"(adjacent pos{i+1}{j} pos{i+1}{j+1})")
        print(f"(adjacent pos{i+1}{j} pos{i}{j})")
        print(f"(adjacent pos{i+1}{j} pos{i+2}{j})")

        # Partie centrale (4 voisins chacun)
        for j in range(1, mat.shape[1]-1):
            j = j+1
            print(f"(adjacent pos{i+1}{j} pos{i}{j})")
            print(f"(adjacent pos{i+1}{j} pos{i+1}{j-1})")
            print(f"(adjacent pos{i+1}{j} pos{i+2}{j})")
            print(f"(adjacent pos{i+1}{j} pos{i+1}{j+1})")

        # Coté droit sauf première et dernière ligne
        j = mat.shape[1]
        print(f"(adjacent pos{i+1}{j} pos{i}{j})")
        print(f"(adjacent pos{i+1}{j} pos{i+2}{j})")
        print(f"(adjacent pos{i+1}{j} pos{i+1}{j-1})")


    # Coin en bas à gauche
    i, j =  mat.shape[0],  1
    print(f"(adjacent pos{i}{j} pos{i-1}{j})")
    print(f"(adjacent pos{i}{j} pos{i}{j+1})")

    # Dernière ligne sauf coins
    for j in range(1, mat.shape[1]-1):
        j += 1
        print(f"(adjacent pos{i}{j} pos{i}{j-1})")
        print(f"(adjacent pos{i}{j} pos{i-1}{j})")
        print(f"(adjacent pos{i}{j} pos{i}{j+1})")

    # Coin en bas à droite
    j = mat.shape[1]
    print(f"(adjacent pos{i}{j} pos{i-1}{j})")
    print(f"(adjacent pos{i}{j} pos{i}{j-1})")

# adjacence_properties(mat2)

In [244]:
def object_of_problem(mat):
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            print(f"pos{i+1}{j+1}")

In [245]:
# (at pos62)
# (obstacle pos42)
# (obstacle pos21)
mat0[3, 1] = 1
mat0[1, 0] = 1
mat0[5, 1] = 8

print("Problème 0 initialisation")
mat0

Problème 0 initialisation


array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 8., 0.]])

In [246]:
# (at pos82)
# (obstacle pos51)
# (obstacle pos52)
# (obstacle pos72)
# (obstacle pos43)
mat1[4, 0] = 1
mat1[4, 1] = 1
mat1[6, 1] = 1
mat1[3, 2] = 1
mat1[7, 1] = 8

print("Problème 1 initialisation")
mat1

Problème 1 initialisation


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 8., 0., 0.]])

In [247]:
mat2[4, 1] = 1
mat2[4, 2] = 1
mat2[4, 3] = 1
mat2[2, 1] = 1
mat2[1, 1] = 1
mat2[0, 0] = 1
mat2[7, 1] = 1
mat2[7, 3] = 1
mat2[12, 0] = 1
mat2[12, 1] = 1
mat2[12, 2] = 1
mat2[13, 1] = 1
mat2[14, 1] = 8

print("Problème 2 initialisation")
mat2

Problème 2 initialisation


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 0.],
       [0., 1., 0., 0.],
       [0., 8., 0., 0.]])